add command

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -14,12 +14,12 @@ jobs:
         run: sudo apt update && sudo apt install -y clang-format
 
       - name: Run clang-format for changed files
+        id: clang-format
         run: |
-          git clang-format --style LLVM --extensions cpp --diff ${{ github.event.pull_request.base.sha }} | tee clang-format-diff.txt
-          if [ -s clang-format-diff.txt ]; then
-            echo "clang-format issues found in the following files:"
-            cat clang-format-diff.txt
-            exit 1
-          else
-            echo "No clang-format issues found."
-          fi
+          git clang-format --style LLVM --extensions cpp --diff ${{ github.event.pull_request.base.sha }} > clang-format-diff.txt
+          echo "result=$?" >> "$GITHUB_OUTPUT"
+
+      - name: Check clang-format result
+        if: steps.clang-format.outputs.result != '0'
+        run: |
+          echo "::error::Clang-format check failed. Please format your code."
